language: rust

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

script:
  cargo build --bin divvunspell --features binaries --release --verbose
#  cargo test --verbose

cache: cargo
