trigger:
- master

jobs:
- job: 'macOS'
  pool:
    vmImage: 'macOS-10.14'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.7'
      addToPath: true
  - script: |
      set -e
      curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain nightly -y
      source $HOME/.cargo/env
      rustup target add aarch64-apple-ios
      rustup target add armv7-apple-ios
      rustup target add i386-apple-ios
      rustup target add x86_64-apple-ios
      cargo lipo --targets aarch64-apple-ios,x86_64-apple-ios,armv7-apple-ios --release -vv
    displayName: 'Do everything'
