[package]
name = "hfst-ospell-rs"
version = "0.1.0"
authors = ["Brendan Molloy <brendan@bbqsrc.net>"]

[lib]
name = "hfstospell"
#crate-type = ["staticlib", "cdylib"]
crate-type = ["dylib"]

[dependencies]
libc = "0.2"
memmap = "0.5"
byteorder = "0.5"
serde = "0.9"
serde_derive = "0.9"
serde-xml-rs = "0.1"
zip = { git = "https://github.com/mvdnes/zip-rs.git", default-features = false }
log = "0.3.7"
env_logger = "0.4.3"

[dev-dependencies]
lazy_static = "*"