[package]
name = "divvunspell"
version = "0.3.0"
authors = ["Brendan Molloy <brendan@bbqsrc.net>"]
edition = "2018"
license = "MIT/Apache-2.0"

[lib]
name = "divvunspell"
crate-type = ["rlib", "staticlib", "cdylib"]

[dependencies]
libc = "0.2"
memmap = "0.7.0"
byteorder = "1.3.1"
serde = "1.0.91"
serde_derive = "1.0.91"
serde-xml-rs = { git = "https://github.com/bbqsrc/serde-xml-rs" }
serde_json = "1.0.39"
zip = { version = "0.5", default-features = false }
log = "0.4.6"
env_logger = "0.6.1"
unic-segment = "0.9.0"
unic-ucd-common = "0.9.0"
parking_lot = "0.8.0"
lazy_static = "1.3.0"
fxhash = "0.2.1"
hashbrown = "0.3"
tempdir = "0.3.7"
lifeguard = "0.6"

clap = { version = "2.33.0", optional = true }

[dev-dependencies]

[profile.release]
debug = true
lto = true

[features]
binaries = ["clap"]
compression = ["zip/deflate"]
