[package]
name = "divvunspell"
version = "0.4.0"
authors = ["Brendan Molloy <brendan@bbqsrc.net>"]
edition = "2018"
license = "MIT/Apache-2.0"

[[bin]]
name = "divvunspell"
required-features = ["binaries"]

[lib]
name = "divvunspell"
crate-type = ["rlib", "staticlib", "cdylib"]

[dependencies]
libc = "0.2"
memmap = "0.7.0"
byteorder = "1.3.1"
serde = "1.0.91"
serde_derive = "1.0.91"
serde-xml-rs = { version = "0.3.1", default-features = false }
serde_json = "1.0.39"
zip = { version = "0.5", default-features = false }
unic-segment = "0.9.0"
parking_lot = "0.8.0"
hashbrown = "0.3"
tempdir = "0.3.7"
lifeguard = "0.6"
ahash = "0.2"

clap = { version = "2.33.0", optional = true }

[dev-dependencies]

[profile.release]
debug = true
lto = true

[features]
binaries = ["clap"]
compression = ["zip/deflate"]
